import { Pages } from "./types"
import { appURL } from "./utils"

// export const images = {
//   [Pages.Welcome1]: `${appURL()}/images/welcome1.png`,
//   [Pages.Welcome2]: `${appURL()}/images/welcome2.png`,
//   [Pages.Welcome3]: `${appURL()}/images/welcome3.png`,
//   [Pages.Welcome4]: `${appURL()}/images/welcome4.png`,
//   [Pages.TermsOrStart]: `${appURL()}/images/termsOrStart.png`,
//   [Pages.Extraction]: `${appURL()}/images/attributes1.png`,
//   [Pages.Arguments1]: `${appURL()}/images/arguments1.png`,
//   [Pages.Arguments2]: `${appURL()}/images/arguments2.png`,
//   [Pages.Arguments3]: `${appURL()}/images/arguments3.png`,
//   [Pages.ExtractionWaiting]: `${appURL()}/images/extractionWaiting.png`,
//   [Pages.ExtractionFailed]: `${appURL()}/images/failedRequest.png`,
//   [Pages.ExtractionExplanation]: `${appURL()}/images/extractionExplanation.png`,
//   [Pages.Scoring]: `${appURL()}/images/scoring.png`,
//   [Pages.Whitelisted]: `${appURL()}/images/whitelisted.png`,
//   [Pages.WhitelistCheckFailed]: `${appURL()}/images/failedRequest.png`,
//   [Pages.Blacklisted]: `${appURL()}/images/blacklisted.png`,
//   [Pages.AllNftsSoldFailed]: `${appURL()}/images/failedRequest.png`,
//   [Pages.OutOfNfts]: `${appURL()}/images/outOfNfts.png`,
//   [Pages.Congrats]: `${appURL()}/images/congrats.png`,
//   [Pages.DatalatteExplanation]: `${appURL()}/images/datalatteExplanation.png`,
// }

export const images = {
  [Pages.ExtractionScoring]:"https://i.imgur.com/xM6rapC.png",
  [Pages.Welcome1]: "https://i.imgur.com/B0sEfNF.png",
  [Pages.Welcome2]: "https://i.imgur.com/Q7LgO6E.png",
  [Pages.Welcome3]: "https://i.imgur.com/zUos842.png",
  [Pages.Welcome4]: "https://i.imgur.com/FQnr20L.png",
  [Pages.TermsOrStart]: "https://i.imgur.com/JnbFX5d.png",
  [Pages.Extraction]: "https://i.imgur.com/XMvVxd1.png",
  [Pages.Arguments1]: "https://i.imgur.com/LXvpFo1.png",
  [Pages.Arguments2]: "https://i.imgur.com/Hrv2Zhe.png",
  [Pages.Arguments3]: "https://i.imgur.com/up5TdBr.png",
  [Pages.ExtractionWaiting]: "https://i.imgur.com/ywHipL3.png",
  [Pages.ExtractionFailed]: "https://i.imgur.com/gfEPwUC.png",
  [Pages.ExtractionExplanation]: "https://i.imgur.com/oq2y9UV.png",
  [Pages.Scoring]: "https://i.imgur.com/kYCZeAw.png",
  [Pages.Whitelisted]: "https://i.imgur.com/mA2SytU.png",
  [Pages.WhitelistCheckFailed]: "https://i.imgur.com/gfEPwUC.png",
  [Pages.Blacklisted]: "https://i.imgur.com/nKetR5C.png",
  [Pages.AllNftsSoldFailed]: "https://i.imgur.com/gfEPwUC.png",
  [Pages.OutOfNfts]: "https://i.imgur.com/t8DVztq.png",
  [Pages.Congrats]: "https://i.imgur.com/zihftss.png",
  [Pages.DatalatteExplanation]: "https://i.imgur.com/BsxklUJ.png",
}
